"""Build a JSON Schema from Python type hints, so a shape is declared once.

The failure this prevents is mundane and extremely common: a dataclass in the
code, a JSON Schema in the prompt, and a field renamed in one but not the
other. The mismatch does not raise; it silently produces `None` in production
three weeks later. Deriving the schema from the dataclass means the prompt and
the parsed object cannot drift apart.

Constraints that have no home in a type hint (minimum, maxLength, pattern,
description) are read from `dataclasses.field(metadata=...)`. The alternative
was a custom `Field()` helper in the pydantic style; rejected because
`metadata` is standard library, already exists for exactly this purpose, and
keeps the dataclass usable by code that has never heard of this module.
"""
from __future__ import annotations

import dataclasses
import enum
import typing
from typing import Any, Dict, List, Optional, Tuple

__all__ = ["schema_from_type", "schema_from_dataclass", "CONSTRAINT_KEYS"]

# Metadata keys copied verbatim onto the generated property schema.
CONSTRAINT_KEYS = (
    "description", "enum", "minimum", "maximum", "minLength", "maxLength",
    "pattern", "minItems", "maxItems", "default", "examples",
)

_PRIMITIVES = {
    str: {"type": "string"},
    bool: {"type": "boolean"},
    int: {"type": "integer"},
    float: {"type": "number"},
    type(None): {"type": "null"},
}


def _unwrap_optional(tp: Any) -> Tuple[Any, bool]:
    """Return (inner_type, is_optional) for Optional[X] / X | None."""
    origin = typing.get_origin(tp)
    # typing.Union covers both Optional[X] and the 3.10+ `X | None` form, which
    # get_origin normalises to types.UnionType; get_args works for both.
    if origin is typing.Union or str(origin) == "<class 'types.UnionType'>":
        args = [a for a in typing.get_args(tp) if a is not type(None)]
        optional = len(args) != len(typing.get_args(tp))
        if len(args) == 1:
            return args[0], optional
        # A genuine multi-member union becomes a type list, which the validator
        # understands. Nested constraints are dropped: there is no sane way to
        # apply `minimum` to a union member and models handle unions badly
        # anyway, so keep the schema honest about being loose here.
        return tuple(args), optional
    return tp, False


def schema_from_type(tp: Any) -> Dict[str, Any]:
    """Map a type annotation onto a JSON Schema fragment."""
    inner, optional = _unwrap_optional(tp)

    if isinstance(inner, tuple):
        types: List[str] = []
        for member in inner:
            types.append(schema_from_type(member).get("type", "string"))
        if optional:
            types.append("null")
        return {"type": types}

    if inner in _PRIMITIVES:
        schema = dict(_PRIMITIVES[inner])
    elif isinstance(inner, type) and issubclass(inner, enum.Enum):
        # Enum members carry their values into the schema so the model sees the
        # exact allowed strings rather than a class name it cannot resolve.
        values = [m.value for m in inner]
        schema = {"type": schema_from_type(type(values[0])).get("type", "string"), "enum": values}
    elif dataclasses.is_dataclass(inner):
        schema = schema_from_dataclass(inner)
    else:
        origin = typing.get_origin(inner)
        args = typing.get_args(inner)
        if origin is typing.Literal:
            schema = {"type": schema_from_type(type(args[0])).get("type", "string"), "enum": list(args)}
        elif origin in (list, set, frozenset, tuple):
            item = args[0] if args else str
            schema = {"type": "array", "items": schema_from_type(item)}
        elif origin is dict:
            value_type = args[1] if len(args) == 2 else str
            schema = {"type": "object", "additionalProperties": schema_from_type(value_type)}
        else:
            # Unknown annotation. A string is the safe default: every model can
            # produce one, and the caller finds out from the schema dump rather
            # than from an exception at prompt-build time.
            schema = {"type": "string"}

    if optional:
        declared = schema.get("type", "string")
        schema["type"] = (declared if isinstance(declared, list) else [declared]) + ["null"]
    return schema


def _docstring_summary(cls: type) -> Optional[str]:
    doc = (cls.__doc__ or "").strip()
    if not doc or doc.startswith(cls.__name__ + "("):
        return None  # the autogenerated dataclass signature, not a real docstring
    return doc.splitlines()[0].strip()


def schema_from_dataclass(cls: type, *, additional_properties: bool = False) -> Dict[str, Any]:
    """Build an object schema for a dataclass, including nested dataclasses.

    `additionalProperties` defaults to False. Models invent plausible extra keys
    ("confidence", "notes") when they are unsure, and an invented key is a
    signal worth surfacing in the retry prompt rather than dropping on the
    floor. Set it True when you genuinely want an open shape.
    """
    if not dataclasses.is_dataclass(cls):
        raise TypeError(f"{cls!r} is not a dataclass")

    hints = typing.get_type_hints(cls)
    properties: Dict[str, Any] = {}
    required: List[str] = []

    for field in dataclasses.fields(cls):
        prop = schema_from_type(hints.get(field.name, str))
        for key in CONSTRAINT_KEYS:
            if key in field.metadata:
                prop[key] = field.metadata[key]
        properties[field.name] = prop

        has_default = (
            field.default is not dataclasses.MISSING
            or field.default_factory is not dataclasses.MISSING  # type: ignore[misc]
        )
        _, optional = _unwrap_optional(hints.get(field.name, str))
        if not has_default and not optional:
            required.append(field.name)

    schema: Dict[str, Any] = {"type": "object", "properties": properties}
    summary = _docstring_summary(cls)
    if summary:
        schema["description"] = summary
    if required:
        schema["required"] = required
    schema["additionalProperties"] = additional_properties
    return schema
